<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Logout</name>
   <tag></tag>
   <elementGuidId>3ef1ca36-bd37-4562-b236-91d4f45332c6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@onclick=&quot;event.preventDefault(); 
                                document.getElementById('logout-form').submit();&quot;]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>li.last > a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>b24cd427-0a51-4152-817e-9d03e1a686a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://ret.waybeo.com/logout</value>
      <webElementGuid>45e0023d-4aed-4bdb-bc65-1f250669dc90</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>event.preventDefault(); 
                                document.getElementById('logout-form').submit();</value>
      <webElementGuid>c4cc9021-905f-479b-897e-f1aacac78b4b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                                Logout
                            </value>
      <webElementGuid>2305cec9-b53b-4d1f-9334-fec20c4e0d6b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;page-body&quot;]/nav[@class=&quot;navbar horizontal-menu navbar-fixed-top&quot;]/div[@class=&quot;navbar-inner&quot;]/ul[@class=&quot;nav nav-userinfo navbar-right&quot;]/li[@class=&quot;dropdown user-profile open&quot;]/ul[@class=&quot;dropdown-menu user-profile-menu list-unstyled&quot;]/li[@class=&quot;last&quot;]/a[1]</value>
      <webElementGuid>f8967317-1a97-4883-9ede-bd5671ffb032</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@onclick=&quot;event.preventDefault(); 
                                document.getElementById('logout-form').submit();&quot;]</value>
      <webElementGuid>5fa0d366-c93d-40a2-a14b-accace59b19c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Change Password'])[1]/following::a[1]</value>
      <webElementGuid>45f54cc3-6f0d-4ea4-b183-7f784be65670</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Customer Callbacks'])[1]/following::a[3]</value>
      <webElementGuid>8d0765bd-bdf9-48f1-a995-95c50ef12b0c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Password Change'])[1]/preceding::a[1]</value>
      <webElementGuid>a3fc5dbc-670b-4521-a0ae-cfc044abe553</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No'])[1]/preceding::a[1]</value>
      <webElementGuid>e3a26ec9-06cc-41d0-b801-fe83959ab193</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Logout']/parent::*</value>
      <webElementGuid>78757453-1458-46ea-ad08-ce7b333f6821</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://ret.waybeo.com/logout')]</value>
      <webElementGuid>0a02bbf6-30e5-4d58-acdd-cde03e89ee47</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//ul[2]/li/ul/li[2]/a</value>
      <webElementGuid>1ccfd04a-2158-4c76-9e12-8285f92605a6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://ret.waybeo.com/logout' and (text() = '
                                Logout
                            ' or . = '
                                Logout
                            ')]</value>
      <webElementGuid>ec11456e-2fc9-4ee7-80cf-18203d01aee8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
